name: "Build BLE Scanner"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build FAP
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: dev
          
      - name: List files after build
        run: |
          echo "Files in current directory:"
          ls -la
          echo "Files in dist directory:"
          ls -la dist/ || echo "No dist directory"
          echo "Looking for .fap files:"
          find . -name "*.fap" -type f
          
      - name: Upload FAP
        uses: actions/upload-artifact@v4
        with:
          name: ble_scanner_fap
          path: "dist/*.fap"
          if-no-files-found: error
